# Generated by Django 5.1.1 on 2024-12-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Home Appliances', 'Home Appliances'), ('TV & Audio', 'TV & Audio'), ('Small Appliances', 'Small Appliances'), ('Computing & Gaming', 'Computing & Gaming'), ('Smart devices', 'Smart devices')], max_length=50),
        ),
    ]
